# Hand-written English glosses for Sino-Korean words that are too rare or
# literary for the open dictionaries (Kengdic / NIKL basic) to cover. These
# are concise glosses intended for the little italic line under each example
# word on a hanja study page. Keys are the hangul word; values are English.
EN = {
 "가가": "a temporary hut, a makeshift shed",
 "가교적": "bridge-building, acting as a bridge",
 "가당": "fitting, suitable",
 "가동비": "operating cost",
 "가련": "pitiful, pitiable",
 "가맹사": "a franchise, a franchised firm",
 "가명제": "a pseudonym system",
 "가변식": "a variable type",
 "가서만금": "a letter worth ten thousand pieces of gold",
 "가설적": "hypothetical",
 "가수요": "artificial, deceptive demand",
 "가옥대장": "a register of houses",
 "가요사": "the history of popular song",
 "가전업계": "the home-appliance industry",
 "가전용품": "home appliances",
 "가족도": "closeness of family, kinship",
 "가증": "an increase, an addition",
 "가처분": "an injunction",
 "가화": "harmony of the household",
 "각박": "harsh, merciless",
 "각설": "putting that aside, enough of that",
 "간경변증": "cirrhosis of the liver",
 "간독": "a liver toxin",
 "간맥": "the liver pulse",
 "간빙기": "an interglacial period",
 "간사장": "a secretary-general",
 "간성지재": "a pillar of the nation",
 "간세지재": "talent that can govern the world",
 "간운보월": "watching the clouds and strolling in moonlight",
 "간취": "to perceive, to discern",
 "간호실": "the nurses' room",
 "갈수기": "a dry season, a time of scarce water",
 "감독상": "the best-director award",
 "감사반": "an audit team",
 "감사실": "the auditing office",
 "감사절": "Thanksgiving",
 "감소분": "the amount by which something decreases",
 "감시대": "a watchtower, a sentry post",
 "감영": "a provincial governor's office",
 "감옥선": "a prison ship",
 "감읍": "weeping with emotion",
 "감찰반": "an inspection team",
 "갑골": "oracle bones",
 "갑술": "the Gapsul year (stem-branch cycle)",
 "갑오": "the Gabo year (of the 1894 reform)",
 "강고": "strong and firm",
 "강공": "a strong attack, an assault",
 "강관": "a steel pipe",
 "강녕": "health and peace",
 "강보합": "a firm but quiet market",
 "강약부동": "uneven, differing in strength",
 "강역": "territory, borders",
 "강유겸전": "combining firmness and gentleness",
 "강포": "violent, brutal",
 "개념화": "conceptualization",
 "개명화": "becoming enlightened, modernizing",
 "개발단": "a development team",
 "개방계": "an open system",
 "개방미": "the charm of openness",
 "개성파": "an individualist (performer)",
 "개시기": "the initial period",
 "개옥개행": "mending one's ways",
 "개요란": "the summary section",
 "개인사": "personal history",
 "객반위주": "the guest upstaging the host",
 "거안사위": "to think of danger in times of peace",
 "건과": "dried fruit",
 "건답법": "dry-field rice cultivation",
 "견강": "firm and strong",
 "견기이작": "to rise to the occasion",
 "견대": "a shoulder strap",
 "견직": "silk weaving",
 "견포": "silk cloth",
 "견현사제": "to see the wise and strive to match them",
 "결성식": "a founding ceremony",
 "결재란": "an approval box",
 "결혼관": "one's view of marriage",
 "겸허감": "a sense of humility",
 "경난": "to pass through hardship",
 "경대부": "high-ranking court nobles",
 "경미": "slight, minor",
 "경변": "hardening of an organ (e.g. cirrhosis)",
 "경술국치": "the national humiliation of 1910",
 "경영난": "management difficulties",
 "경제사": "economic history",
 "계급성": "class character",
 "계도적": "instructive, guiding",
 "계몽사상": "Enlightenment thought",
 "계서적": "sequential, genealogical",
 "계유년": "the Gyeyu year (stem-branch cycle)",
 "계축": "the Gyechuk year (stem-branch cycle)",
 "계획과": "the planning division",
 "고려조": "the Goryeo dynasty",
 "고령지": "highlands",
 "고전극": "a classical drama",
 "고촉": "a tall candle",
 "고침이와": "to rest easy, free of worry",
 "고혼": "a lonely spirit",
 "곡읍": "bitter weeping",
 "곤액": "distress, hardship",
 "공가": "an empty house",
 "공납": "tribute payment",
 "공납적": "tributary",
 "공납제": "a tribute system",
 "공모주": "publicly offered shares",
 "공전론": "a theory of idle running",
 "공전제": "a public-fields system",
 "과부댁": "a widow's household",
 "과원": "an orchard",
 "과표": "the taxable base",
 "관노": "a government slave",
 "관련국": "the countries concerned",
 "관료배": "the bureaucratic crowd",
 "관리사": "a management professional",
 "관민": "government and people",
 "관부": "a government office",
 "관서": "the Pyeongan (northwestern) region",
 "관속": "government functionaries",
 "관엽": "ornamental foliage",
 "관찰기": "an observation report",
 "관치": "rule by bureaucrats",
 "광고계": "the advertising world",
 "괴상망측": "bizarre beyond imagining",
 "교술시": "a didactic poem",
 "교양과": "the liberal-arts department",
 "교위": "a military officer rank",
 "교육지": "an education magazine",
 "교환기": "a telephone exchange",
 "구구식": "mechanical, by rote",
 "구득난": "hard to come by",
 "구만": "ninety thousand",
 "구면지기": "an old acquaintance",
 "구십구": "ninety-nine",
 "구십사": "ninety-four",
 "구십삼": "ninety-three",
 "구십칠": "ninety-seven",
 "구합": "a haphazard, improper union",
 "국량": "state grain",
 "국록": "a government stipend",
 "국악과": "the traditional-music department",
 "국태민안": "a country at peace and its people safe",
 "군계": "the military sphere",
 "군치소": "a county seat",
 "군포": "a cloth tax levied for the army",
 "군현": "counties and prefectures",
 "궁장": "a bow-maker",
 "귀면": "a demon's face",
 "귀빈관": "a VIP reception hall",
 "귀선": "a return line",
 "규격성": "standardization",
 "근무조": "a work shift, a duty crew",
 "금석지감": "mixed feelings over the changes of time",
 "금욕적": "ascetic, self-denying",
 "급모": "urgent recruitment",
 "급반등": "a sharp rebound",
 "기계과": "the mechanical-engineering department",
 "기괴": "bizarre, grotesque",
 "기괴망측": "absurdly bizarre",
 "기복성": "ups and downs, undulation",
 "기온차": "a temperature difference",
 "기천": "deceiving heaven; fraud",
 "기초반": "the beginners' class",
 "기필": "certainly, surely",
 "길복": "good fortune",
 "남벌": "a southern expedition",
 "남순": "a royal tour of the south",
 "남정": "a southern campaign",
 "남조": "the Southern Dynasties",
 "내유외강": "soft within, firm without",
 "내편": "the inner part",
 "노력비": "the cost of effort",
 "농경적": "agrarian",
 "농량": "the year's harvest of grain",
 "농어가": "farming and fishing households",
 "농요": "farmers' work songs",
 "농호": "a farming household",
 "누증": "a steady increase",
 "능숙": "skilled, adept",
 "다우": "rainy, wet",
 "다채": "colorful, varied",
 "단과": "a single discipline",
 "단임": "a single term of office",
 "단편성": "the quality of being fragmentary",
 "단편적": "fragmentary, piecemeal",
 "당돌": "audacious, brazen",
 "당사주": "fortune-telling by one's natal horoscope",
 "당수": "a party leader",
 "당중앙": "a party's central committee",
 "대리암": "marble",
 "대성전": "the great shrine hall of a Confucian academy",
 "대아": "the Great Elegance (a section of the Book of Odes)",
 "대축척": "large-scale (of a map)",
 "대투매": "heavy wholesale selling",
 "도약기": "a period of rapid growth",
 "도예과": "the ceramics department",
 "도착적": "perverse, twisted",
 "도호부": "a frontier military command",
 "독실": "sincere, devoted",
 "돈사": "a pigsty",
 "동양란": "an Oriental orchid (Cymbidium)",
 "동지사": "a Winter-Solstice envoy",
 "동헌": "a county magistrate's office",
 "둔전": "garrison farmland",
 "둔탁": "dull-witted, blunt",
 "등과": "passing the civil-service examination",
 "등차": "an arithmetic difference",
 "마상재": "equestrian acrobatics",
 "만고풍상": "the trials of a lifetime",
 "만사휴의": "it is all over, all is lost",
 "망극": "boundless, utmost",
 "망월": "the full moon",
 "매개충": "a disease vector",
 "매매춘": "prostitution",
 "맹랑": "preposterous, shocking",
 "면려": "to encourage, to spur on",
 "명륜당": "a Confucian school's lecture hall",
 "명부전": "the hall of the underworld",
 "명수필": "a fine personal essay",
 "명철": "wise and clear-sighted",
 "모색창연": "the dusk deepening into gloom",
 "모월": "the final month",
 "목이": "wood-ear mushroom",
 "무역량": "trade volume",
 "무치": "shameless",
 "무투표": "an uncontested vote",
 "묵가": "the Mohist school of thought",
 "문묘": "the Confucian shrine",
 "미래불": "the Buddha of the future",
 "미심": "a lingering doubt",
 "미측심천": "of unfathomable depth",
 "민속극": "folk drama",
 "반사막": "a semi-desert",
 "반식민": "anti-colonial",
 "반윤리적": "unethical",
 "반환일": "the date of return",
 "방명": "your honored name",
 "방천": "a river embankment",
 "배불": "the rejection of Buddhism",
 "백가": "the Hundred Schools of thought",
 "백곡": "all kinds of grain",
 "백단": "white sandalwood",
 "백단목": "the sandalwood tree",
 "백두옹": "the pasqueflower (Anemone)",
 "백발로옹": "a white-haired old man",
 "백십이": "one hundred and twelve",
 "백아절현": "breaking one's lute after losing a close friend",
 "백억": "ten billion",
 "백오": "one hundred and five",
 "백이십팔": "one hundred and twenty-eight",
 "백이지렴": "the incorruptible honor of the sage Boyi",
 "백팔": "one hundred and eight",
 "백팔십": "one hundred and eighty",
 "법륜": "the Wheel of the Dharma",
 "변풍이속": "to transform customs and mores",
 "병립": "standing side by side, coexisting",
 "복술": "the art of divination",
 "본존": "the principal deity of a shrine",
 "본존불": "the principal Buddha image",
 "부모구존": "with both parents still alive and well",
 "부세": "taxation, levies",
 "부역장": "a site of forced labor service",
 "분묘": "a grave, a tomb",
 "분호": "the smallest fraction",
 "붕괴설": "a theory of collapse",
 "붕락": "collapse, caving in",
 "붕우": "a friend",
 "붕우유신": "friends keeping faith with one another",
 "붕우책선": "friends urging one another to do right",
 "비가열": "unheated",
 "비견": "comparable, on a par",
 "비굴": "servile, submissive",
 "비축미": "stockpiled rice",
 "사기단": "a morale unit",
 "사달이이의": "words suffice simply to convey meaning",
 "사륜": "four-wheeled",
 "산괴": "a mountain massif",
 "산봉": "a mountain peak",
 "산야": "mountains and fields",
 "삼억": "three hundred million",
 "삼현": "a three-stringed zither",
 "상량": "the ceremony of raising the main ridgepole",
 "상전벽해": "the world transformed beyond recognition",
 "서무과": "the general-affairs section",
 "서사": "narrative",
 "서사극": "epic drama",
 "서서": "slowly, gradually",
 "석괴": "a mass of rock",
 "선건전곤": "to shake heaven and earth",
 "선관": "an election commission",
 "선승": "a Zen monk",
 "선우": "the Chanyu (ruler of the Xiongnu)",
 "선택법": "a method of selection",
 "세조": "an ancestor-founder (of a dynasty)",
 "소국": "a small state",
 "소집처": "an assembly point",
 "속음": "the popular, everyday pronunciation",
 "숙질": "uncle and nephew",
 "순검": "a patrol officer",
 "숭앙": "reverence, adoration",
 "숭유": "venerating Confucianism",
 "시묘": "keeping vigil at a parent's grave",
 "시발역": "the origin station, the terminus",
 "시야비야": "is it so, or is it not",
 "식재": "planting (trees)",
 "신중론": "the cautious position",
 "신질서": "a new order",
 "신축년": "the Sinchuk year (stem-branch cycle)",
 "신해혁명": "the Xinhai Revolution",
 "십륙": "sixteen",
 "십전대보환": "a restorative herbal tonic pill",
 "십현": "the ten sages",
 "악폐": "a bad abuse, an evil practice",
 "앙불괴어천": "to be able to face the heavens without shame",
 "애련": "loving attachment",
 "애모심": "affectionate admiration",
 "애증": "love and hate",
 "애첩": "a beloved concubine",
 "약탈당": "being plundered",
 "양광": "sunlight",
 "양극적": "polarized, bipolar",
 "양돈": "pig farming",
 "양돈업": "the pig-raising business",
 "양목": "growing timber",
 "어언간": "in the meantime",
 "여관촌": "an inn district",
 "여남월단": "the caustic critical style of the Ruxian school",
 "여유감": "a sense of ease and leisure",
 "역구내": "inside the station grounds",
 "역려": "a traveler's inn",
 "역질": "an epidemic disease",
 "열등반": "a remedial, lower-level class",
 "영령": "the spirit of the departed",
 "영설지재": "poetic talent",
 "오니": "mud, sludge",
 "오니층": "a layer of silt",
 "오륙백": "five or six hundred",
 "오불관언": "it is none of my concern",
 "오석": "black stone",
 "오악": "the Five Sacred Mountains",
 "오호": "alas",
 "오호애재": "alas and woe",
 "오호통재": "alas, how tragic",
 "옥리": "a jailer, a prison warden",
 "온유돈후": "gentle and sincere",
 "와우형": "coiled like a snail's shell",
 "와해적": "disintegrating, falling apart",
 "왈시왈비": "approving and dismissing this way and that",
 "외곽선": "an outer ring road",
 "요배": "to bow from afar",
 "우심": "exceedingly, especially severe",
 "우화등선": "to take wing and rise as an immortal",
 "운니지차": "a world of difference",
 "운위": "so-called, as it was said",
 "원천우인": "to blame heaven and other people",
 "월단평": "a severe, sweeping criticism",
 "월삭": "the first day of the lunar month",
 "유유낙낙": "easygoing and content",
 "유정": "compassion, warmth of feeling",
 "유태교": "Judaism",
 "유훈": "a deceased elder's teachings",
 "을미": "the Eulmi year (stem-branch cycle)",
 "을사오적": "the five 'traitors' of the year 1905",
 "을유": "the Eulyu year (stem-branch cycle)",
 "을축": "the Eulchuk year (stem-branch cycle)",
 "을해": "the Eulhae year (stem-branch cycle)",
 "이계": "another world",
 "이발지시": "an arrow once shot",
 "이수자": "one who has completed a course of study",
 "인내천": "Man is Heaven (a Cheondogyo tenet)",
 "일속": "a single grain of millet",
 "일신우일신": "to renew oneself day by day",
 "일적": "accumulating day by day",
 "임란": "the Japanese invasion of 1592",
 "임오년": "the Imo year (stem-branch cycle)",
 "입적": "to be naturalized, to gain citizenship",
 "자괴감": "a feeling of shame",
 "자괴지심": "a pang of self-reproach",
 "자목련": "the purple magnolia",
 "자의적": "arbitrary, willful",
 "잠간": "for a moment, briefly",
 "저렴": "low in price, cheap",
 "적멸": "the stillness of nirvana",
 "전불습호": "have I not practiced what I was taught?",
 "점복": "divination",
 "점증": "a gradual increase",
 "정혜": "meditative concentration and wisdom",
 "조용조": "the Zu–Yong–Diao (rent, labor, cloth) tax system",
 "종횡적": "horizontal and vertical",
 "좌평": "a high official rank of the Baekje kingdom",
 "죄의유경": "to judge leniently when guilt is unclear",
 "준재": "a person of outstanding talent",
 "준행": "to faithfully observe, to follow",
 "중차대": "grave and weighty",
 "지록위마": "calling a deer a horse (deliberate falsification)",
 "지혜자": "a wise person",
 "차안": "this mortal world",
 "창대": "prosperous, thriving",
 "창성": "flourishing",
 "청량": "cool and refreshing",
 "청렴도": "a measure of integrity",
 "청천": "a clear sky",
 "최강수": "a winning, decisive move",
 "최강자": "the very strongest",
 "축록": "to contend for supremacy",
 "쾌청": "beautifully clear weather",
 "파견관": "an envoy, a dispatched official",
 "파수군": "sentry troops",
 "패류": "shellfish",
 "피체포자": "an arrested person",
 "필역": "completion of a task",
 "하곡": "a river valley",
 "한재": "a drought disaster",
 "행리": "luggage, baggage",
 "향리": "a local village clerk",
 "향악": "native Korean music",
 "헌물": "a votive offering",
 "헌헌장부": "a dignified, stalwart man",
 "호연": "vast (of a noble moral spirit)",
 "호접몽": "the butterfly dream (Zhuangzi)",
 "화곡": "grain crops",
 "화액": "calamity, misfortune",
 "화창": "warm and bright (of weather)",
 "효일": "the morning sun",
 "훼상": "damage, defacement, injury",
 "휘호": "bold, flowing brush calligraphy",
}
# Second pass: words that only had Korean dictionary definitions or were still
# empty after the open dictionaries were tried. Classical idioms and rare
# compounds translated concisely.
EN2 = {
 "갑남을녀": "common, ordinary people",
 "경복궁": "Gyeongbokgung Palace",
 "경천동지": "earth-shaking, sensational",
 "호계삼소": "\"the three laughs at Tiger Brook\" (a classic scene)",
 "진퇴유곡": "caught in a bind, in a dilemma",
 "고군분투": "fighting alone, a lone struggle",
 "궁극적": "ultimate, in the end",
 "고금동서": "all times and places, past and present",
 "극기복례": "mastering the self and restoring courtesy",
 "결사반대": "opposition to the death",
 "동남동녀": "boys and girls",
 "무릉도원": "an earthly paradise",
 "견리사의": "think of what is right when eyeing profit",
 "계림": "an old name for Silla",
 "만경창파": "the vast blue ocean",
 "계명구도": "resorting to low crafty tricks",
 "고장난명": "you cannot clap with one hand",
 "일모도원": "so much to do in so little time",
 "각자무치": "no one can have everything",
 "고립무원": "isolated and without help",
 "금시초문": "hearing (it) for the first time",
 "문일지십": "hear one and grasp ten",
 "미생지신": "inflexible, over-literal trust",
 "경세제민": "governing the world and helping the people",
 "백가쟁명": "a hundred schools contend",
 "건보": "national health insurance",
 "무소부지": "knowing everything, omniscient",
 "문방사우": "the four treasures of the scholar's study",
 "공평무사": "fair and impartial",
 "독서삼도": "the three essentials of reading",
 "골육상쟁": "kin at odds with one another",
 "교학상장": "teaching and learning grow together",
 "거래선": "a customer, a business client",
 "구국간성": "a bulwark who saves the nation",
 "세비": "annual government expenditure",
 "박장대소": "clapping and roaring with laughter",
 "미풍양속": "fine customs and good traditions",
 "견위수명": "to give one's life when the nation is in danger",
 "수연": "even so, nevertheless",
 "우수사려": "grief and anxious brooding",
 "만수무강": "boundless longevity",
 "애걸복걸": "begging and pleading humbly",
 "언즉시야": "what you say is right",
 "금의야행": "walking at night in brocade — wasted success",
 "숙약": "which of the two, how does one compare",
 "汝等여": "",
 "여등": "you all",
 "송구영신": "seeing out the old year and welcoming the new",
 "삼성오신": "reflecting on oneself three times a day",
 "오비삼척": "hard up, no leisure to mind others",
 "오합지중": "a disorderly rabble",
 "교외별전": "conveying the truth beyond words",
 "내우외환": "troubles within and dangers without",
 "망운지정": "longing for one's parents far away",
 "군웅할거": "rival warlords carving up power",
 "경이원지": "to keep a respectful, wary distance",
 "견위치명": "to lay down one's life in a crisis",
 "안거위사": "stay vigilant even in easy times",
 "고육지책": "a drastic self-denying expedient",
 "교우이신": "treating friends with trust",
 "사군이충": "serving one's ruler with loyalty",
 "살신성인": "to die in fulfilling one's virtue",
 "개장": "reopening, refitting, opening",
 "개항장": "a treaty port",
 "저수지": "a reservoir",
 "유아독존": "\"alone in all the world\" — supreme self-regard",
 "시종일관": "consistent from beginning to end",
 "좌불안석": "too anxious to sit still",
 "주경야독": "farming by day and reading by night",
 "단도직입": "straight to the point",
 "매처학자": "a hermit who keeps plum and crane as kin",
 "백년하청": "waiting forever for the impossible",
 "여삼추": "longing like three autumns in a day",
 "사단취장": "shedding faults and keeping strengths",
 "담판": "negotiations",
 "백팔번뇌": "the one hundred and eight afflictions",
 "필부지용": "reckless, foolhardy courage",
 "필부필부": "ordinary men and women",
 "대서특필": "to splash it across the headlines",
 "항사": "an everyday, constant practice",
 "기호지세": "no turning back once begun",
 "동가홍상": "given equal terms, choose the finest",
 "고목생화": "a withered tree bursting into bloom",
 "병환": "illness, sickness",
 "공경대부": "the ministers and high officials",
 "과대망상": "delusions of grandeur",
 "금상첨화": "adding flowers to brocade",
 "금의환향": "returning home in glory",
 "정녕": "certainly, for sure",
 "단국": "the kingdom founded by Dangun",
 "당면": "cellophane (glass) noodles",
 "사상누각": "a castle built on sand",
 "전율": "trembling with fear",
 "명복": "blessings in the afterlife",
 "농목": "farming and stock-raising",
 "묘당": "the royal shrine and halls of state",
 "백미": "the cream of the crop, the pick",
 "박람강기": "widely read with a strong memory",
 "식소사번": "overworked and underfed, exhausting oneself",
 "고복격양": "a peaceful age of plenty",
 "어두봉미": "the best bits — head of fish, tail of fowl",
 "귀비": "a high-ranking royal consort",
 "사족": "gilding the lily, an unnecessary addition",
 "백사": "white sand",
 "속미": "millet and rice",
 "혼정신성": "attending to one's parents morning and night",
 "앙급지어": "innocent bystanders caught in a disaster",
 "지어지앙": "collateral damage, guilt by association",
 "유야무야": "vague, neither here nor there",
 "부위원장": "a vice-chairperson",
 "백발삼천장": "exaggerated far beyond the truth",
 "기승전결": "the arc of a composition (opening, development, turn, close)",
 "호접지몽": "the butterfly dream — the transience of life",
 "각주구검": "absurdly rigid and inflexible",
 "억조창생": "the countless people of the world",
 "모수자천": "to volunteer, to put oneself forward",
 "계군일학": "a crane among chickens — one who stands out",
 "군계일학": "standing out from the crowd",
 "함흥차사": "a mission from which there is no return",
 "만사형통": "everything going smoothly and well",
 "고희": "the age of seventy",
 # --- rare compounds (second pass) ---
 "가거주": "temporary residence",
 "개교회": "a local congregation",
 "길기": "an auspicious, lucky air",
 "각본난": "the difficulty of woodblock printing",
 "소두": "a small bushel (a small measure)",
 "녹금": "green brocade",
 "면리": "villages and townships",
 "가면관": "a hall of masks",
 "모고신종": "the dusk drum and the dawn bell",
 "물경": "never fear, do not be alarmed",
 "답배": "to return a bow",
 "방벌적": "punitive (of deposing an unjust ruler)",
 "가변선": "a variable line",
 "봉공": "public service, devotion to one's duty",
 "계서화": "arrangement into ranks, hierarchization",
 "각서설": "the memorandum theory",
 "매석": "selling only reluctantly (of shares)",
 "담시": "discussing poetry",
 "신승": "a narrow victory",
 "개아": "the individual self",
 "가입안": "a motion for admission, a joining bill",
 "결여론": "the theory of absence",
 "결여설": "the doctrine of a lack",
 "부연구": "an associate researcher",
 "열들이다": "to accept gladly",
 "부귀처영": "a wife shares her husband's rise to glory",
 "상오": "the morning",
 "귀와": "to return home and rest",
 "고소원": "just as I had wished",
 "고읍": "an ancient town",
 "도로이목": "to trade furtive glances on the road, too afraid to speak",
 "세이": "washing one's ears (refusing to listen to corruption)",
 "자고저": "the height of letters",
 "관료전": "land allotment for officials",
 "관광전": "a sightseeing exhibition",
 "가전사": "a home-appliance firm",
 "군항제": "a naval-port festival",
 "교종": "a religious denomination",
 "농주": "home-brewed farming liquor",
 "모주": "mother liquor, mash",
 "송죽매": "the pine, the bamboo and the plum",
 "건중탕": "a warming herbal tonic",
 "분지화": "branching",
 "감구지회": "nostalgia for the old days",
 "가집": "a song collection",
 "차치": "to set something aside for now",
 "만사천": "fourteen thousand",
 "개촌": "founding a village",
 "취입": "to blow in",
 "육향": "the aroma of meat",
 "각형": "a rectangular, angular shape",
 "갑호": "first class, grade A",
 "건각": "strong, sturdy legs",
 "결각": "a notch, an indentation",
 "산괴형": "massif-shaped, blocky",
 "경구금": "detention, barring access",
 "백근": "a hundred catties (a great weight)",
 "운근성풍": "wielding the axe with masterly ease",
 "근엄화": "making stricter, tightening discipline",
 "사기당": "to be duped, to be scammed",
 "낭가": "the home of a married woman's own family",
 "백답": "a poor, low-yield paddy",
 "대본소": "a shop that lends out books",
 "나견": "fine silk and gauze",
 "백란과": "the white-orchid family",
 "개력": "calendar reform",
 "대통력": "a calendar (the Day-Tong one)",
 "우렬": "superiority and inferiority",
 "우선룡": "a dragon coiling to the right (geomancy)",
 "주누선": "the main line of tears",
 "매재": "a transmission medium",
 "오묘제": "the system of five ancestral shrines",
 "모방도": "the degree of imitation",
 "백중세": "a close, evenly matched contest",
 "벽류": "a clear green stream",
 "고보": "a senior comprehensive (high school)",
 "무보": "dance notation",
 "봉거대공": "the terrace stands empty after the phoenix has flown",
 "반비판": "counter-criticism",
 "빙물": "betrothal gifts",
 "빙화폐": "ceremonial betrothal gifts",
 "기무사": "a coordination (intelligence) office",
 "개사": "each company",
 "모사론": "a theory of imitation",
 "제사명": "the name used in ancestral sacrifice",
 "칠삭": "the seventh lunar month",
 "검색기": "a search machine, a search engine",
 "서이행지": "to act with forbearance and forgiveness",
 "소도": "the Sodo, the sacred sanctuary of the Jin state",
 "발순": "setting out on patrol",
 "아세": "the winter solstice",
 "어언": "in the meantime, all the while",
 "공역": "public service or labor; airspace",
 "어목연석": "passing off fish eyes as pearls",
 "오상고절": "lofty integrity that defies the frost",
 "모우미성": "not yet fledged, not yet grown",
 "사석음우": "marksmanship that pierces stone",
 "솔성지위도": "following one's nature is the Way",
 "양이": "the Western barbarians",
 "월장": "to climb over a wall",
 "관재": "the misfortunes of official life",
 "면조": "an exemption from land tax",
 "건준": "establishing a standard",
 "도증주인": "the thief resents the householder",
 "군지": "a county chronicle",
 "천답": "trampling, treading underfoot",
 "체포죄": "an arrest for the offense of unlawful restraint",
 "우체": "postal delivery",
 "입초": "an import surplus",
 "원목경침": "a wooden pillow that kept one from oversleeping while studying",
 "타락상": "a state of moral degradation",
 "선기자덕": "the best riders are the ones who fall (overconfidence)",
 "투설": "a confession, to pour out one's words",
 "방판": "door-to-door sales",
 "폐일언": "to put it all in one word",
 "일언이폐지": "in a word, to sum up briefly",
 "노폭": "the width of a road",
 "함담": "saltiness and freshness (of water)",
 "속현": "a county under another's jurisdiction",
 "주현": "the leading county",
 "대혈": "a large cavity",
 "위협당": "to be threatened",
 "구화지문": "the disaster that careless words bring",
 "고래희": "rare since ancient times (a life of seventy)",
 "금송령": "an order protecting the royal pine forests",
 "숙능어지": "who could possibly stop it",
 "배척당": "those excluded and shunned",
 "선기자타": "pride comes before a fall — the overconfident stumble",
 "촉밀": "candle wax and honey",
 "의지하다탁": "to rely on, to lean on someone",
 "수탈당": "to be stripped and robbed",
 "토설": "to pour out a confession",
 "경창": "a singing contest",
}
